# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 455d5a18a248fe5d13052d799b70590f64d67fda0969eb28246863042400595110bb0d64df74bd878fe2533b98b8e7c3dfc0eaf9b4285829abb6910fe407e4cb

test:
  secret_key_base: bc649d71fce6f57942ba0cea15874f83b1faf63f6ab29ecce7d3bea98c9524655ac8121b4b46fcfca67673175afc7c2e7ee52f146154d1b6b816be809a8ea5a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
